FAKE NEWS CLASSIFIER Using LSTM

Dataset Link:https://www.kaggle.com/c/fake-news/data#


Steps to be Followed:
1. Load the Data
2.Independent and Dependent Feature Seperation
3.Cleaning the Data Using Stemming and Stopwords
4.One Hot Representation
5.Fix Sentence Length to be Constant
6.Embedding Layer 
7.LSTM Model Creation
8.Train Test Split
9.Model Training
10.Performance Metrics and Accuracy

In [39]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_csv('train.csv',error_bad_lines=False,engine='python')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
Skipping line 11827: unexpected end of data


In [41]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [42]:
df.isnull().sum()

id           0
title      322
author    1101
text        25
label        0
dtype: int64

In [43]:
df.shape

(11825, 5)

In [44]:
df=df.dropna()#Dropping Nan Values

In [45]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [46]:
df.shape

(10402, 5)

In [47]:
X= df.drop('label',axis=1)

In [48]:
X.shape

(10402, 4)

In [49]:
y= df['label']

In [50]:
y.shape

(10402,)

In [51]:
import tensorflow as tf

In [53]:
tf.__version__

'2.8.2'

In [55]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


In [57]:
### VOCAB SIZE
voc_size = 5000

ONE HOT ENCODING

In [58]:
messages = X.copy()

In [59]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [62]:
messages.reset_index(inplace=True)

In [63]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
10397  11820  11820  Texas Elector Expects Massive Corruption Relat...   
10398  11821  11821  Neocon Trotskyite Hannity Wants America Back O...   
10399  11822  11822  No Search Warrant Yet: FBI Can’t Move On Email...   
10400  11823  11823  #NoDAPL Spills Over: Musicians Boycott Dakota ...   
10401  11824  11824  A View of the Syrian War From the Golan Height...   

                             author  \
0                     Darrell Lucus   
1                   Daniel J. Flynn   
2                Consortiumnews.com   
3                   Jessica Purkiss   
4                    Howard Portnoy   
...                             ...   
10397                   Dave Hodges   
10398  Norm Bimstein (UID 71489130)   
10399                Michelle Oxman   
10400                 Kit O'Connell   
10401                   Robert Fisk   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
10397  Previous Texas Elector Expects Massive Corrupt...  
10398  Report Copyright Violation Neocon Trotskyite H...  
10399  No Search Warrant Yet: FBI Can’t Move On Email...  
10400  Videos #NoDAPL Spills Over: Musicians Boycott ...  
10401   A View of the Syrian War From the Golan Heigh...  

[10402 rows x 5 columns]

In [64]:
import nltk
import re
from nltk .corpus import stopwords

In [65]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [69]:
# DATA PREPROCESSING

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(messages)):
  print(i)
  review = re.sub('[^a-zA-Z]',' ', messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
5402
5403
5404
5405
5406
5407
5408
5409
5410
5411
5412
5413
5414
5415
5416
5417
5418
5419
5420
5421
5422
5423
5424
5425
5426
5427
5428
5429
5430
5431
5432
5433
5434
5435
5436
5437
5438
5439
5440
5441
5442
5443
5444
5445
5446
5447
5448
5449
5450
5451
5452
5453
5454
5455
5456
5457
5458
5459
5460
5461
5462
5463
5464
5465
5466
5467
5468
5469
5470
5471
5472
5473
5474
5475
5476
5477
5478
5479
5480
5481
5482
5483
5484
5485
5486
5487
5488
5489
5490
5491
5492
5493
5494
5495
5496
5497
5498
5499
5500
5501
5502
5503
5504
5505
5506
5507
5508
5509
5510
5511
5512
5513
5514
5515
5516
5517
5518
5519
5520
5521
5522
5523
5524
5525
5526
5527
5528
5529
5530
5531
5532
5533
5534
5535
5536
5537
5538
5539
5540
5541
5542
5543
5544
5545
5546
5547
5548
5549
5550
5551
5552
5553
5554
5555
5556
5557
5558
5559
5560
5561
5562
5563
5564
5565
5566
5567
5568
5569
5570
5571
5572
5573
5574
5575
5576
5577
5578
5579
5580
5581
5582
5583
5584
5585
5586
5587
5588
5589
5590
5591

In [73]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

ONE HOT ENCODING

In [74]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[3865, 3265, 2397, 4591, 959, 4350, 2629, 2914, 97, 2445],
 [3431, 3937, 4048, 76, 2158, 1229, 362],
 [2737, 798, 3344, 1310],
 [1721, 774, 4382, 2430, 1474, 4806],
 [1950, 2158, 86, 4187, 27, 4419, 2158, 4692, 820, 1235],
 [4551,
  539,
  2379,
  2140,
  1777,
  1995,
  282,
  4924,
  1358,
  549,
  3694,
  3533,
  4943,
  2516,
  362],
 [1819, 2240, 211, 21, 562, 2222, 1378, 1827, 3122, 4483, 3192],
 [694, 1745, 2868, 980, 2176, 1366, 1995, 3546, 3122, 4483, 3192],
 [2622, 224, 3691, 4730, 1915, 681, 765, 723, 1995, 3927],
 [1091, 3863, 734, 1531, 2101, 2791, 2019, 4929],
 [3803, 2358, 2324, 4014, 1213, 1499, 2537, 4288, 1432, 2105, 3553],
 [2430, 4240, 959, 681, 1995, 2176],
 [3617, 3644, 672, 220, 2009, 404, 4076, 1815, 1402],
 [2442, 1618, 4072, 3369, 1624, 3393, 3863, 3122, 4483, 3192],
 [1612, 3795, 1755, 3718, 2507, 3122, 4483, 3192],
 [3421, 1025, 2113, 283, 3194, 3397, 2096, 4505, 3605, 2170],
 [3419, 1056, 3937],
 [4206, 4214, 3630, 1698, 1995, 162, 4081, 362],
 [4228, 630,

In [75]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [76]:
onehot_repr[1]

[3431, 3937, 4048, 76, 2158, 1229, 362]

EMBEDDING REPRESENTATION

In [77]:
sent_length=20# Making all sentences of same size =20;can make it different as well.
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2914   97 2445]
 [   0    0    0 ... 2158 1229  362]
 [   0    0    0 ...  798 3344 1310]
 ...
 [   0    0    0 ... 3214  213 1970]
 [   0    0    0 ... 3471 1784 1457]
 [   0    0    0 ...  974 2146 2912]]


In [78]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 3431, 3937, 4048,   76, 2158, 1229,  362], dtype=int32)

MODEL CREATION

In [81]:
embedding_vector_features = 40# Hyperparameter Can be Modified
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))# No of Nuerons Can play
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [82]:
len(embedded_docs),y.shape

(10402, (10402,))

In [83]:
X_final = np.array(embedded_docs)
y_final = np.array(y) 

In [84]:
X_final.shape,y_final.shape

((10402, 20), (10402,))

In [86]:
# TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.3,random_state=42)

MODEL TRAINING

In [87]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
114/114 [==============================] - 12s 17ms/step - loss: 0.4247 - accuracy: 0.7999 - val_loss: 0.2205 - val_accuracy: 0.9052
Epoch 2/10
114/114 [==============================] - 1s 11ms/step - loss: 0.1529 - accuracy: 0.9407 - val_loss: 0.1978 - val_accuracy: 0.9125
Epoch 3/10
114/114 [==============================] - 1s 12ms/step - loss: 0.0912 - accuracy: 0.9672 - val_loss: 0.2255 - val_accuracy: 0.9202
Epoch 4/10
114/114 [==============================] - 1s 12ms/step - loss: 0.0533 - accuracy: 0.9816 - val_loss: 0.2452 - val_accuracy: 0.9109
Epoch 5/10
114/114 [==============================] - 1s 11ms/step - loss: 0.0294 - accuracy: 0.9912 - val_loss: 0.3400 - val_accuracy: 0.9016
Epoch 6/10
114/114 [==============================] - 1s 12ms/step - loss: 0.0135 - accuracy: 0.9963 - val_loss: 0.4038 - val_accuracy: 0.9026
Epoch 7/10
114/114 [==============================] - 1s 10ms/step - loss: 0.0108 - accuracy: 0.9977 - val_loss: 0.4951 - val_accuracy: 0.909

PERFORMANCE METRICS and ACCURACY

In [88]:
y_pred=model.predict(X_test)

In [89]:
y_pred = np.where(y_pred > 0.5,1,0)# Can play with 0.5 this is threshold
# CAN use AUC ROC Curve

In [90]:
from sklearn.metrics import confusion_matrix

In [91]:
confusion_matrix(y_test,y_pred)

array([[1634,  164],
       [ 141, 1182]])

In [99]:
from sklearn.metrics import accuracy_score
print("The Accuracy of the Model is:",accuracy_score(y_test,y_pred)*100,"%")

The Accuracy of the Model is: 90.22749118872156 %


In [95]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.91      0.91      1798
           1       0.88      0.89      0.89      1323

    accuracy                           0.90      3121
   macro avg       0.90      0.90      0.90      3121
weighted avg       0.90      0.90      0.90      3121



ADDITIONAL METHODS

In [102]:
#USING DROPOUT LAYERS decreases Overfitting
from tensorflow.keras.layers import Dropout
embedding_vector_features = 40# Hyperparameter Can be Modified
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))# No of Nuerons Can play
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm_3 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [103]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
114/114 [==============================] - 5s 13ms/step - loss: 0.4301 - accuracy: 0.7960 - val_loss: 0.2130 - val_accuracy: 0.9145
Epoch 2/10
114/114 [==============================] - 1s 12ms/step - loss: 0.1633 - accuracy: 0.9348 - val_loss: 0.1913 - val_accuracy: 0.9257
Epoch 3/10
114/114 [==============================] - 1s 13ms/step - loss: 0.1051 - accuracy: 0.9599 - val_loss: 0.2621 - val_accuracy: 0.9196
Epoch 4/10
114/114 [==============================] - 1s 12ms/step - loss: 0.0818 - accuracy: 0.9698 - val_loss: 0.2737 - val_accuracy: 0.9161
Epoch 5/10
114/114 [==============================] - 1s 11ms/step - loss: 0.0526 - accuracy: 0.9817 - val_loss: 0.2400 - val_accuracy: 0.9122
Epoch 6/10
114/114 [==============================] - 1s 7ms/step - loss: 0.0343 - accuracy: 0.9883 - val_loss: 0.3333 - val_accuracy: 0.9071
Epoch 7/10
114/114 [==============================] - 1s 7ms/step - loss: 0.0210 - accuracy: 0.9937 - val_loss: 0.2676 - val_accuracy: 0.9112
E

In [106]:
y_pred=model.predict(X_test)
y_pred = np.where(y_pred > 0.6,1,0)
confusion_matrix(y_test,y_pred)

array([[1626,  172],
       [ 120, 1203]])

In [107]:
print("The Accuracy of the Model with Dropout Layers is:",accuracy_score(y_test,y_pred)*100,"%")

The Accuracy of the Model with Dropout Layers is: 90.64402435116949 %
